### ISSUE TITLE
Singly_Linked_List_implementation.c가 실행이 되지않는 문제 그리고 해결

### ISSUE THREAD

**Issue by exgs** [nadarm/42-algorithm#1]
int main(void)
{
	t_node **begin_list = (t_node **)malloc(sizeof(t_node *));
	***begin_list = 0;**
	printf("size = %d\n", list_size(*begin_list));
	list_add1(begin_list, 0);
        ...
}

메인함수에서 *begin_list = NULL; 를 추가해줘야 실행됩니다!

**Comment by nadarm** [comment]
첫 이슈 감사합니다!
수정했어요~
