### ISSUE TITLE
System("leaks ....")가 malloc의 메모리 누수를 못 잡기도하나요?

### ISSUE THREAD

**Issue by exgs** [nadarm/42-algorithm#10]
![캡처_2020_05_12_20_40_54_240](https://user-images.githubusercontent.com/56223639/81683289-e7009d00-9490-11ea-93e1-b17976985dd1.png)
   
nadaram님의 tester를 작성하신 implementation.c 로 돌린 결과입니다.
제 생각에는 5개가 발생해야할 것 같은데, 0 leaks 가 나옵니다.  
(init()으로 생성한 t_stack =1개, strdup()으로 생성한 data 와  해당 t_node = 4개)
leaks가 못잡는 부분이 있는걸까요?
slack에서 leaks이 아닌, valgrind로 메모리체크하는 것을 보았습니다. leaks 보다는 valgrind가
정확 할까요?

**Comment by nadarm** [comment]
leaks에서는 메모리에 접근이 가능한 상태이면(변수에 담겨 있으면) memory leak이라고 판단하지 않습니다

그래서 접근이 불가능하도록 
leaks를 호출하기전에
`stack = 0;` 코드를 추가하면 접근이 불가능해져서 릭으로 판단해줍니다

참고로 코드가 업데이트 전 내용이네요
최신 상태로 업데이트 추천드립니다!

**Comment by exgs** [comment]
먼저 stack=0이면, leaks가 변수 stack에 담긴 주소가 없기 때문에, stack->top으로 부터 연결된 t_node에 있는 data값까지도 접근이 불가능해져서 메모리 누수를 확인할 수 없어집니다.
따라서 0 leak이 나타난다고 이해했습니다.

코드를 최신버전으로 업데이트를 하고, 관련사항을 체크하고있는데요.
![캡처_2020_05_14_01_05_08_174](https://user-images.githubusercontent.com/56223639/81837250-95830b80-957f-11ea-8a7e-473aa9539d09.png)
다른 부분은 변경없이 free_stack()부분만 주석처리하여, 실행시켜보면 또 다시 0 leaks가 나옵니다.
그래서, slack에 나와있는대로 valgrind를 cluster에 설치하고 메모리누수를 확인해본 결과.
![캡처_2020_05_14_01_11_20_92](https://user-images.githubusercontent.com/56223639/81837449-d844e380-957f-11ea-95ab-e3472f18fbe8.png)
definitely lost와 indirectly lost 부분은 메모리누수가 확실히 난 부분이라고 해석 할 수 있을 것 같습니다.  
제가 질문드리고싶은 것은 두가지인데요.
1.  leaks가 잡지 못하는 메모리누수를 보였는데, 과정상에서 올바르지못한부분이 있는지 궁금합니다.

2. 이러한 오류가 나지않도록 leaks를 올바르게 사용하는 방법이 있을까요? 사용자가 "leaks"를 조심스럽게 제어하는 방식으로쓰면 충분히 메모리누수를 잡을 수 있을 것 같다는 생각이듭니다.

valgrind는 목적파일을 만들고 valgrind의 복잡한 명령어를 사용해야지만 메모리누수를 확인한다는 점에서 무거운느낌이 듭니다. 하지만, "leaks"는 굉장히 간단해서 사용하기 쉽기때문에 간단한 메모리누수는 leaks로 체크하고 싶기 때문입니다.

**Comment by nadarm** [comment]
valgrind의 still reachable이 leaks에서 메모리릭에 포함되지 않는다는 말이였습니다
```
#include <stdlib.h>
int main(void)
{
    void *p = malloc(10);
    p = 0; // 이부분을 주석처리하면 still reachable 상태라 릭이 아닌 걸로 판단
    system("leaks a.out");
    return (0);
}
```

그런데 stack의 테스트 코드에서는 메모리릭으로 잡히질 않으니 이상하네요 
전에 테스트할 땐 메모리릭으로 잘 잡아줬던 것 같은데 왜 이러는걸까요...

더 찾아보고 원인을 찾으면 알려드리겠습니다 😭

**Comment by exgs** [comment]
와 이거 진짜 모르겠습니다. 간단한 int main() 함수내에서는 void *p = malloc(10); p = 0; 는 메모리누수가 발생하게 만들 수도 있지만,   stack_linked_list를 테스트하고있는 소스코드는 어떤 포인터를 NULL로 만들어버림에 따라 메모리누수가 있음에도 detecting 하지 못하는 경우도 있는 것 같네요..
GG..

**Comment by exgs** [comment]
## 생각

"_먼저 heap2가 free 된 후 똑같은 크기인 heap3를 할당해보니 같은 주소에 할당이 되었는데요, 힙의 할당을 좀 더 효율적으로 하기 위해, 반환된 heap 영역의 크기를 기억해놨다가 같은 크기의 할당 요청이 들어오면 이전 영역을 재사용합니다_."   에서 힌트를 얻었습니다.  
출처 : https://bpsecblog.wordpress.com/2016/10/06/heap_vuln/

## 증명

```c
#include <stdio.h>
#include <stdlib.h>

int main(void)
{
    char* t1;
    char* s1;

    t1 = malloc(256);
    free(t1);
    
    /* 1번 스위치 */
	// t1 = NULL;

    /* 2번 스위치 */
    s1 = malloc(256); //메모리 할당공간의 크기가 t1과 같은경우
    // s1 = malloc(257);
    
	printf("test(first malloc) : %p\n",t1);
	printf("string(second malloc) : %p\n",s1);
    
	s1 = 0;
    //변수를 통해 메모리주소에 접근하지 못하도록 NULL처리하기, free(s1)도 적용되지않음
	free(s1);
	system("leaks a.out > leaks_result; cat leaks_result | grep leaked");
    return 0;
}
```

1번 스위치는 free() 후에 <u>메모리 주소를 NULL 처리하는 것</u>  
2번 스위치는 s1 에 할당하는 메모리의 크기를 <u>t1과 같은 크기로 하거나, 그보다 큰 크기로 하는 것</u>   
3.번 스위치는 free(s1); 이전에 s1 = NULL; 

1. 1번 스위치 OFF(주석처리) , 2번스위치 malloc(256)  
   메모리의 크기가 같다면(비슷하면) 같은 메모리주소에 재할당하는 것을 볼 수 있습니다.   
   leaks 명령어에 의한 메모리누수는 없다고 나옵니다.
2.  1번 스위치 OFF(주석처리), 2번스위치 malloc(257)  
   메모리 크기가 크지만, 큰 차이가 나지않으면, 같은 메모리주소에 재할당하는 것을 볼 수 있습니다  
   (단, malloc(1000)이런 경우에는 메모리주소가 달라진다.)  
   leaks 명령어에 의한 메모리누수가 있다고 나옵니다.  
   s1에 256Byte 보다 t1이 1Byte 큰 257Byte를 할당받으면서 실제로, 메모리  누수는 256+16**(minimum unit)** = 272Byte가 발생합니다. 
3. 1번 스위치 OFF(주석처리), 2번 스위치 malloc(200);  
   메모리 크기가 작으면, 같은 메모리주소에 재할당하는 것을 볼 수 있습니다.  
   leaks 명령어에 의한 메모리누수는 없다고 나옵니다.
4. 1번 스위치 ON(주석처리 X)   
   이제 변수를 통해 메모리가 할당된 주소를 접근할 수 있는 변수는 없다.  
   --> 2번 스위치에 관계없이 메모리누수는 항상 발생한다.

## 적용

```c
	stack_push(stack, strdup("f22222"));
	printf("size = %d\n", stack_size(stack));
	printf("peek->data = %s\n", stack_peek(stack) ? stack_peek(stack)->data : 0);
	free(stack);
	
	free_stack(stack, free);
	char *abc = malloc(1000) //malloc 할당 값을 조절하면서, 위 증명과정을 적용해볼 수 있다.
	abc = 0;
	system("leaks a.out > leaks_result; cat leaks_result | grep leaked");
	return (0);
```



## 결과해석

leaks는 할당된 메모리로 접근가능한 포인터변수가 없다면 leaks로 판단한다.  
반대로 free()되지 않아도 접근 가능한 포인터변수가 있다면 leaks로 판단하지 않는다.  
 위 **증명**에서 보인것은 접근 가능함에도 leaks를 잡아주지 못하는 경우도 있는데, 같거나 작은(<=) 메모리공간을 같은 메모리주소에 재할당하는 경우이다.  

## 문제점 및 고찰

leaks에게 있어서 접근이 불가능하다는 것에 대해  명확하게 알지 못했다.  

1. 포인터의 주소를 변경시키는 것(stack = NULL)을 의미하는 것?
2. free() 선언함으로써, 컴퓨터가 해당 주소에 대한 관리를 하지않고 언제든지 덮어쓰여질 수 있는 상태가 되는 것? 

int main() 소스코드에서 간단히 malloc을 하고, 포인터의 주소를 NULL처리 하는 경우에는 1번의 케이스가 맞다.  
하지만, 복잡한 소스코드(nadaram's test_main.c)에서는 오히려 포인터의 주소를 NULL처리하면 leak이 발생하지 않고  
free(stack)만 할 경우, node에 의한 메모리 누수가 발생한다.

근본적인 문제는 해결하지 못하였다.   
접근이 가능한 포인터가 없음에도(stack = 0) leaks로 판단하지 않는 경우에 대한 가능성을 알아낼 수 없었다.  
(nadaram's test_main.c에서 실질적으로 문제가 됬던 부분)

**Comment by exgs** [comment]
## 생각

"_먼저 heap2가 free 된 후 똑같은 크기인 heap3를 할당해보니 같은 주소에 할당이 되었는데요, 힙의 할당을 좀 더 효율적으로 하기 위해, 반환된 heap 영역의 크기를 기억해놨다가 같은 크기의 할당 요청이 들어오면 이전 영역을 재사용합니다_."   에서 힌트를 얻었습니다.  
출처 : https://bpsecblog.wordpress.com/2016/10/06/heap_vuln/

## 증명

```c
#include <stdio.h>
#include <stdlib.h>

int main(void)
{
    char* t1;
    char* s1;

    t1 = malloc(256);
    free(t1);
    
    /* 1번 스위치 */
	// t1 = NULL;

    /* 2번 스위치 */
    s1 = malloc(256); //메모리 할당공간의 크기가 t1과 같은경우
    // s1 = malloc(257);
    
	printf("test(first malloc) : %p\n",t1);
	printf("string(second malloc) : %p\n",s1);
    
	s1 = 0;
    //변수를 통해 메모리주소에 접근하지 못하도록 NULL처리하기, free(s1)도 적용되지않음
	free(s1);
	system("leaks a.out > leaks_result; cat leaks_result | grep leaked");
    return 0;
}
```

1번 스위치는 free() 후에 <u>메모리 주소를 NULL 처리하는 것</u>  
2번 스위치는 s1 에 할당하는 메모리의 크기를 <u>t1과 같은 크기로 하거나, 그보다 큰 크기로 하는 것</u>   
3.번 스위치는 free(s1); 이전에 s1 = NULL; 

1. 1번 스위치 OFF(주석처리) , 2번스위치 malloc(256)  
   메모리의 크기가 같다면(비슷하면) 같은 메모리주소에 재할당하는 것을 볼 수 있습니다.   
   leaks 명령어에 의한 메모리누수는 없다고 나옵니다.
2.  1번 스위치 OFF(주석처리), 2번스위치 malloc(257)  
   메모리 크기가 크지만, 큰 차이가 나지않으면, 같은 메모리주소에 재할당하는 것을 볼 수 있습니다  
   (단, malloc(1000)이런 경우에는 메모리주소가 달라진다.)  
   leaks 명령어에 의한 메모리누수가 있다고 나옵니다.  
   s1에 256Byte 보다 t1이 1Byte 큰 257Byte를 할당받으면서 실제로, 메모리  누수는 256+16**(minimum unit)** = 272Byte가 발생합니다. 
3. 1번 스위치 OFF(주석처리), 2번 스위치 malloc(200);  
   메모리 크기가 작으면, 같은 메모리주소에 재할당하는 것을 볼 수 있습니다.  
   leaks 명령어에 의한 메모리누수는 없다고 나옵니다.
4. 1번 스위치 ON(주석처리 X)   
   이제 변수를 통해 메모리가 할당된 주소를 접근할 수 있는 변수는 없다.  
   --> 2번 스위치에 관계없이 메모리누수는 항상 발생한다.

## 적용

```c
	stack_push(stack, strdup("f22222"));
	printf("size = %d\n", stack_size(stack));
	printf("peek->data = %s\n", stack_peek(stack) ? stack_peek(stack)->data : 0);
	free(stack);
	
	free_stack(stack, free);
	char *abc = malloc(1000) //malloc 할당 값을 조절하면서, 위 증명과정을 적용해볼 수 있다.
	abc = 0;
	system("leaks a.out > leaks_result; cat leaks_result | grep leaked");
	return (0);
```



## 결과해석

leaks는 할당된 메모리로 접근가능한 포인터변수가 없다면 leaks로 판단한다.  
반대로 free()되지 않아도 접근 가능한 포인터변수가 있다면 leaks로 판단하지 않는다.  
 위 **증명**에서 보인것은 접근 가능함에도 leaks를 잡아주지 못하는 경우도 있는데, 같거나 작은(<=) 메모리공간을 같은 메모리주소에 재할당하는 경우이다.  

## 문제점 및 고찰

leaks에게 있어서 접근이 불가능하다는 것에 대해  명확하게 알지 못했다.  

1. 포인터의 주소를 변경시키는 것(stack = NULL)을 의미하는 것?
2. free() 선언함으로써, 컴퓨터가 해당 주소에 대한 관리를 하지않고 언제든지 덮어쓰여질 수 있는 상태가 되는 것? 

int main() 소스코드에서 간단히 malloc을 하고, 포인터의 주소를 NULL처리 하는 경우에는 1번의 케이스가 맞다.  
하지만, 복잡한 소스코드(nadaram's test_main.c)에서는 오히려 포인터의 주소를 NULL처리하면 leak이 발생하지 않고  
free(stack)만 할 경우, node에 의한 메모리 누수가 발생한다.

근본적인 문제는 해결하지 못하였다.   
접근이 가능한 포인터가 없음에도(stack = 0) leaks로 판단하지 않는 경우에 대한 가능성을 알아낼 수 없었다.  
(nadaram's test_main.c에서 실질적으로 문제가 됬던 부분)

**Comment by nadarm** [comment]
이슈가 해결되기 전까지는 계속 오픈해놓겠습니다...
ㅠㅠ

**Comment by exgs** [comment]
안녕하세요.  
leaks를 잘 사용하고싶은 마음에 좀 더 탐구해보았지만, leaks 메뉴얼을 읽지않고 경험칙상으로 규칙을    알아내는데에는 한계가 있었습니다.   
가장 큰 문제는 함수를 호출함으로써 <u>함수내에서 malloc이 일어날 경우</u>에 leaks가 줄어들기도하고 늘어나기도하는데에 있습니다.  
저는 valgrind를 쓰는 편이 낫겠다고 결론 지었습니다.  
저는 더이상 leaks command에 미련이 없어서 issue는 close해도 괜찮을 것 같습니다.  
아래 코드에서 주석을 위에서 부터 하나씩 제거하면서 leaks의 거동을 보면, 중구난방 뛰는 leaks값을 확인 할 수 있습니다.  

```c
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

typedef struct	s_node
{
	void			*data;
	struct s_node	*next;
}				t_node;

typedef struct	s_stack
{
	unsigned int	size;
	t_node			*top;
}				t_stack;

t_node	*stack_peek(t_stack *stack)
{
	if (stack == 0)
		return (0);
	return (stack->top);
}

t_node	*create_elem(void *data)
{
	t_node *node;

	node = (t_node *)malloc(sizeof(t_node));
	if (node == 0)
		return (0);
	node->data = data;
	node->next = 0;
	return (node);
}

int	stack_push(t_stack *stack, void *data)
{
	t_node *new_node;

	if (stack == 0 || (new_node = create_elem(data)) == 0)
		return (0);
	new_node->next = stack->top;
	stack->top = new_node;
	stack->size++;
	new_node = NULL;
	return (1);
}

int main()
{
	t_stack *stack;
	t_node *node;
	t_node *node2;
	t_node *new_node;
	
	stack = malloc(sizeof(t_stack));
	node = malloc(sizeof(t_node));
	node2 = malloc(sizeof(t_node));
	
	/*첫번째 노드 push*/
	// stack->top = node;
	// node->data = strdup("a");
	// printf("peek->data = %s\n", stack_peek(stack) ? stack_peek(stack)->data : 0);
	// printf("----------------------------------------------------\n");
	
	/*두번째 노드 push*/
	// node2->next = stack->top;
	// node2->data = strdup("b");
	// stack->top = node2;
	// printf("peek->data = %s\n", stack_peek(stack) ? stack_peek(stack)->data : 0);
	// printf("----------------------------------------------------\n");
	
	/*세번째 노드 push*/
	//방법(1) main함수 내에서 넣기
	// new_node = malloc(sizeof(t_node));
	// if (stack == 0 || (new_node = create_elem(strdup("cc"))) == 0)
	// 	return (0);
	// new_node->next = stack->top;
	// stack->top = new_node;
	// stack->size++;
	// printf("peek->data = %s\n", stack_peek(stack) ? stack_peek(stack)->data : 0);
	// printf("----------------------------------------------------\n");
	
	//방법(2) 만들어놓은 함수를 이용해서 넣기
	// stack_push(stack, strdup("e223"));
	// printf("peek->data = %s\n", stack_peek(stack) ? stack_peek(stack)->data : 0);
	// printf("----------------------------------------------------\n");
	
	node = NULL;
	node2 = NULL;
	stack = NULL;
	new_node = NULL;
	
	system("leaks a.out > leaks_result; cat leaks_result | grep leaked");
}
```
