### ISSUE TITLE
무방향 그래프 (인접행렬) 질문드립니다!

### ISSUE THREAD

**Issue by 365kim** [nadarm/42-algorithm#11]
안녕하세요!
저는 지금 그래프 에서 무방향 그래프를 학습 중인데요 ✏️ 
예제 구현 중 궁금한 점이 생겨 질문드립니다!
<br>

## 질문1 : graph_traversal 구현 중 순회방법

https://github.com/nadarm/42-algorithm/blob/1ab4dbed3006c0194df6825408460685b292d635/graph/undirected_matrix/implementation/graph.c#L129-L165

순회 중 혹시 143행에서 i 값을 `i = 0`대신에 `i = curr + 1` 로 해도 괜찮을까요?
무방향 그래프는 행렬이 대칭이고 순회를 항상 0부터 시작하기 때문에 가능할 것 같은데 뭔가 놓치고 있는게 있을까해서 질문 드립니다.
<p><img src="https://user-images.githubusercontent.com/60066472/86479540-52773480-bd87-11ea-9af0-34b2a1cd3424.PNG" width="300"></p>
(그림출처:https://lasthere.tistory.com/15)
<br>

## 질문2 : make_graph을 구현 중 메모리해제

https://github.com/nadarm/42-algorithm/blob/1ab4dbed3006c0194df6825408460685b292d635/graph/undirected_matrix/implementation/graph.c#L111-L127

120행에서와 같이 data[i]는 매개변수로 전달받는 free_data라는 함수로 해제시켜주고 있습니다. (121행에서 matrix[i]가 라이브러리의 free함수로 해제시켜주는 것과 대조됩니다)

https://github.com/nadarm/42-algorithm/blob/1ab4dbed3006c0194df6825408460685b292d635/graph/undirected_matrix/implementation/graph.c#L190-L217

그런데 make_graph을 구현할 때에 프로토타입에는 별다른 매개변수 없고, 그래프 해제 시 213행과 같이 라이브러리의 free함수를 전달하게 됩니다.
그렇다면 free_graph함수에 매개변수로 주어지던 free_data라는 함수는 라이브러리의 free함수와 기능이 같은 것인가? 하는 의문이 들어 질문 드립니다.

감사합니다! 42알고리즘 만세!

**Comment by nadarm** [comment]
질문1
(0 - 2 - 1)로만 연결된 그래프를 생각해보시면 좋을 것 같습니다!

질문2
그래프의 데이터가 void형 포인터들이라 모든 형태의 데이터든 저장할 수 있어요
make_graph에서는 문자열이기 때문에 단순 free함수로 메모리 해제를 할 수 있지만
복잡한 형태의 데이터라면 free함수로는 메모리 누수가 생길 수 있습니다
예)
```
strcut my_struct {
    char *str;
    char *str2;
}
my_struct *my = 메모리할당 + 초기화;
free(my);  // my->str과 my->str2에서 메모리 누수가 발생할 수 있음
```

**Comment by 365kim** [comment]
오우 바로바로 이해가 됩니다 설명짱짱!
make_graph에서 주는 데이터가 문자열이기 때문에 가능한 것이었군요
친절한 설명 감사드립니다~!!
42알고리즘 만세~~~
