### ISSUE TITLE
double linked list에서 ex00 구조체에서 오타가 있습니다

### ISSUE THREAD

**Issue by exgs** [nadarm/42-algorithm#4]
typedef struct	s_node
 {
 	int		data;
 	struct s_node	*prev;
 	struct s_node	*next;
 }		t_node;

 typedef struct	s_linked_list
 {
 	unsigned int	size;
 	t_node		*head;
 	t_node		*tail;
 }		**t_linekd_list;**-> t_linked_list;

-------
번외로 질문이 있는데, 혹시 알고계시다면 답변 부탁드립니다.
t_linked_list * new= malloc(sizeof(t_linked_list));
new = NULL;
free(new);
new가 동적할당된 메모리주소를 가리키지않으니깐 이런식으로 free를 하면, 메모리누수가 나는 것은
주어진 문제를 풀면서 알게되었습니다!

leaks에 대해 조금더 알아보고자 몇가지 장난을 쳐봤는데요.
위 코드처럼 할 경우 grademe.sh 에서 2 leaks를 띄워줍니다.
그리고 new에 NULL 할당하지않고 free(new); 를 해줄 시에 0 leaks 가 됩니다.
제가 궁금한건 왜 1(개)단위씩이 아니라 2 (개)단위씩 메모리누수가 나는 건가요??
넘어갈법한데 nadaram님이 알고계실 수도 있겠다는 생각이 들어서 질문드립니다. 감사합니다

**Comment by nadarm** [comment]
이슈 감사합니다😃
오타 빨리 수정 할께요~
질문하신건 코드와 leaks 결과 내용을 올려주시면 알 수 있을 것 같아요

**Comment by exgs** [comment]
> 질문하신건 코드와 leaks 결과 내용을 올려주시면 알 수 있을 것 같아요

![캡처_2020_04_17_19_52_03_871](https://user-images.githubusercontent.com/56223639/79562243-af970e80-80e5-11ea-9883-8d9665ce89e8.png)
메모리누수가 나지않는 것을 확인하였습니다.
![캡처_2020_04_17_19_52_29_1](https://user-images.githubusercontent.com/56223639/79562254-b887e000-80e5-11ea-904b-a87d276f02da.png)
이 사진은 구조체 t_linked_list(목록) 만 free(list);를 주석처리함으로써 메모리누수가 나게했는데,

vscode command에 1leaks가 아닌 2leaks가 뜨는게 이해가되지않았었습니다..
grademe.sh의 gcc에 -fsanitize=address를 넣으면 뭔가 정보를 얻을 수있다는 얘기를 들어서, 해보았습니다.
![캡처_2020_04_17_20_02_45_645](https://user-images.githubusercontent.com/56223639/79562716-6eebc500-80e6-11ea-9439-a3d9f6d62f96.png)
명확한이유는 아직도모르지만, malloc을 하면 메모리공간외에 memeory scanner도 힙영역에 저장된다라고 지금 상황에서는 그렇게 이해하고있습니다!
틀린부분이나 추가적으로 알려주실 코멘트가 있을까요??

**Comment by nadarm** [comment]
71번 줄에서 링크드리스트에 있는 내용을 전부 비우고
72번 줄에서 새로운 노드 하나를 추가합니다
그럼 메모리 릭이 일어난 건 t_linked_list 1개와 72번 줄에서 추가한 t_node 1개로 2개가 맞습니다!

**Comment by exgs** [comment]
아아... 왜그리 성급하게 결론을 내렸을까요ㅠㅠ
잘못하면 오개념을 진리마냥 가지고있을 뻔 했습니다.
다음엔 이런일 없도록 좀 더 주의깊게 살펴봐야겠네요!

+자료구조와 알고리즘에 대해서 공부해보고 싶다는 생각이 있었는데, 그냥 이미지로 개념만 익히면서 제대로 알지못하고 넘어가는 느낌이였는데, 만드신 컨텐츠 덕분에 재밌게 배우고 있습니다~
감사합니다!

**Comment by nadarm** [comment]
관심 가져주시고 피드백도 해주시니 제가 더 감사합니다 :)
