### ISSUE TITLE
5.tree 중 접두사트리 insert 구현 관련 질문드립니다

### ISSUE THREAD

**Issue by 365kim** [nadarm/42-algorithm#5]
nadarm님 안녕하세요
문제 올려주시는 덕분에 감사히 학습하고 있습니다.

5.tree에서 접두사트리 예제 구현에 어려움이 있어 질문드립니다.

테스트 결과를 보면 insert함수가 문제인 것 같습니다.

nadarm님의 테스트 메인문에서 str하나 insert할때마다 trie가 출력되도록 해주셨는데
저의 경우 테스트 결과에서 첫번째 str인 "abc"부터 나오지 않습니다.

insert이전에 필요한 create_node함수나 init함수에 문제있수도 있어 여러번 봤지만 아무래도 insert함수가 문제일 것 같습니다.

아래는 제 insert 코드입니다. "abc"가 새로 들어간다고 가정했을 떄 따라가보면 잘 들어갈 것 같고, nadarm님의 코드와도 기능이 비슷하게 짜인 것 같은데 출력이 전혀 안되는 답답한 상황입니다... 코드 한 번 봐주시면 정말 감사하겠습니다..!

```
#include "trie.h"

bool trie_insert(t_trie *trie, char *str)
{
	t_node	*curr;
	int     i;
	int     j;

	if (trie == NULL || str == NULL || str[0] == '\0')
		return (false);
	j = str[0] - 'a';
	curr = (*trie)[j];
	if (curr == NULL)
		curr = create_elem();
	i = 1;
	while (str[i])
	{
		j = str[i] - 'a';
		curr = curr->next[j];
		if (curr == NULL)
			curr = create_elem();
		i++;
	}
	curr->finish = true;
	return (true);
}
```

답변 미리 감사드립니다!

**Comment by nadarm** [comment]
curr == null일때 새로 노드를 생성하긴 하지만 이전 노드에 연결해주는 작업이 없어서 삽입이 안되고 있어요
```
curr = curr->next[j];
if (curr == NULL)
 	curr = create_elem();
```
이 부분을 수정해보시면 될 것 같습니다
