### ISSUE TITLE
(circle_linked_list) 의문점이 있습니다.

### ISSUE THREAD

**Issue by exgs** [nadarm/42-algorithm#6]
1.  list_find
```c
int		list_find(t_linked_list *list, void* data, int (*cmp)(void *data1, void *data2))
{
	t_node		*curr;
	unsigned int	i;

	if (list == 0 || cmp == 0 || (curr = list->head) == 0)
		return (-1);
	i = 0;
	while (i < list->size)
	{
		if (cmp(curr->data, data) == 0)
			return (i);
		i++;
		curr = curr->next;
	}
	return (-1);
}
```

list_find 함수의 코드입니다.  
현재 cmp 함수포인터로 int (\*cmp)(void \*data1, void \*data2)로 표현하였는데,  
함수내에서 data1 과 data2의 사용이 없으니, 그냥 int(\*cmp)(void *, void *) 로 표현하는게 낫지않나요?  
아니면 남겨놓은 이유가 있는 건가요??

**Comment by nadarm** [comment]
특별한 이유는 아니고 문제의 함수 시그니쳐와 동일하게 작성하다보니 list_find 함수만 그렇게 된 것 같습니다
int (*cmp)(void *, void *) 표현이 더 가독성이 좋은 것 같아 수정하였습니다!
감사합니다
