### ISSUE TITLE
README.md파일 오기

### ISSUE THREAD

**Issue by 365kim** [nadarm/42-algorithm#7]
안녕하세요

README.md 파일에서 4358번 생태학이 4258번 생태학으로 잘못 표기되어있습니다
(링크는 4358번으로 잘 연결됩니다!)

항상 감사드립니다 (--)(__)

**Comment by nadarm** [comment]
어떤 디렉토리의  리드미 파일인지 알려주시면 감사하겠습니다 ㅠㅠ

**Comment by nadarm** [comment]
tree/README.md의 22번 줄 부분 수정하였습니다!
이슈 감사합니다!
