### ISSUE TITLE
(circle_linked_list) list_add에 대한 질문이 있습니다.

### ISSUE THREAD

**Issue by exgs** [nadarm/42-algorithm#8]
1. list_add(t_linked_list *list, void *data, int n)에서 n = 0 일때, list_add의 return 값에 대해서 질문이 있습니다.
   list_add 의 return은 "생성된 요소의 인덱스를 반환 합니다. (0 혹은 양수)" 라고 되어있습니다.
    test.c  

   ```c
   // test.c file의 83line
   for (int i = 0; i < 5; ++i) {
       printf("list_add return value = %d, list_size = %d\n",
   				list_add(list, strdup(test_data[index++]), 0), list_size(list));
       print_list(list);
   	}
   ```

   이 부분에서 list_add( , , 0)의 명령은 index가 0인 곳에 add를 시키는 것이니깐 reutrn 값이 0이 되어야한다고 생각 해서 코드를 짯으나,  
   nadaram님의 implementation.c에 의하면 n=0 일때는 return : list_size(list) -1을 return 합니다.  
   다시말하면, list->head 접근, 계속 ->next로  한바퀴를 돌기 마지막에 생성시킨 양수값을 return합니다.  
   이유가 있을까요? 그냥 관점의 차이이겠지만, 궁금해서 질문드립니다   
   가볍게 받아주시면 감사하겠습니다!

+제 코드

```c
int ft_add_sub(t_linked_list *list, t_node *add_list, int n)
{
	t_node *prev;
	t_node *next;
	int index_n;

	index_n = n % list_size(list);
	if (index_n >= 0)
	{
		prev = list_get(list, index_n-1);
		next = prev->next;
		prev->next = add_list;
		add_list->prev = prev;
		next->prev = add_list;
		add_list->next = next;
		if (index_n == 0)
			return(list_size(list) - 1); //그래서 이 부분을 추가했습니다.
		return (index_n);
	}
	next = list_get(list, index_n + 1);
	prev = next->prev;
	next->prev = add_list;
	add_list->next = next;
	prev->next = add_list;
	add_list->prev = prev;
	return (list_size(list) + index_n);
}

int list_add(t_linked_list *list, void *data, int n)
{
	t_node *add_list;

	if (list == NULL || data == NULL)
		return(-1);
	add_list = create_elem(data);
	list->size++;
	if(list_size(list) == 0)
	{
		list->head = add_list;
		add_list->next = add_list;
		add_list->prev = add_list;
		return (0);
	}
	return(ft_add_sub(list, add_list,n));
}
```

**Comment by exgs** [comment]
현재 window에서는 implementation에 있는 코드와 제 코드를 test.c로 컴파일하여 비교하면,
값이 동일하게나오지만,
macos에서 돌리는 경우 문제가 발생합니다.
1. segementation fault 문제
window에서는 막힘없이 print가 찍혔는데, 원인불명의 segmentation fault가 만들어짐
2. 똑같은 코드를 macos에서 실행시 
```for (int i = test_data_size / 7 * 3; i < test_data_size / 7 * 4; ++i) {
		printf("index = %d, list_add return value = %d, list_size = %d\n", test_index[i], list_add(list, strdup(test_data[i]), test_index[i]), list_size(list));
		print_list(list);
	}
``` 이 함수 코드 부분에서  list_size 값이 window와 다르게 나오는 상황
(아마 printf에서 나열된 함수의 연산순서와 관련 있는 것 같음)

이렇게 해결되지않은 문제들이 있고, 이러한 것부터 해결해야할 것 같아서
이 질문은 스스로 close합니다. (testcase가 많아지니, 어렵네요..)

**Comment by nadarm** [comment]
마지막 인덱스를 반환하는 건 말씀하신대로 구현하기 나름이라 그렇습니다
문제를 만들고 직접 구현하다보니 생각하기에 따라 달라지는 부분이 너무 많더라고요
그래서 그런 부분을 조금이라도 줄이고자 문제 상단에 몇가지 규칙을 추가 했었습니다.
```list의 head가 바뀌는 경우는 4가지 입니다.
빈 list에 노드를 추가할 때(list의 size가 0에서 1이 될 때)
head가 가리키는 노드가 삭제될 때(해당 노드의 next가 head가 됩니다.)
head를 이동하는 함수 list_move_head_to_next를 사용할 때
head를 이동하는 함수 list_move_head_to_prev를 사용할 때
```
리스트가 비어있지 않은 상태에서 0번에 추가 -> 헤드는 바뀌지 않으니까 헤드부터 인덱스를 계산하면 -1이 된다고 생각했어요

**Comment by exgs** [comment]
@nadarm 
list의 head의 index가 무조껀 0 의 위치를 자치한다고 생각하니, 그렇게 구현이 되는군요
circle linked list 관련함수를 초안으로 작성했을 때는 보이지않았던것이(스스로 debugging test를 했음에도..)
test.c로 내용을 다시 살펴보니, 디테일한 부분이 새롭게보이네요!

+처음에는 list_size를 벗어난 int index는 예외처리하였는데, test.c에서는 size의 범위를 넘어가도 cycle을 돌면서 index 계산을 하는게 수학에서 각도계산하는 것처럼 느껴져서 재밌었네요
답변 감사합니다!!
