### ISSUE TITLE
안녕하세요! 질문이 있습니다.

### ISSUE THREAD

**Issue by taelee42** [nadarm/42-algorithm#9]
42서울에서 공부하고 있는 taelee라고 합니다.
올려주신 자료로 자료구조를 공부하고 있습니다.
너무 좋은 자료 올려주셔서 감사드립니다!!

현재 stack을 공부하고 있습니다.
array로 구현한 stack에서 stack_clear함수에 대해 질문이 있습니다.
메인문을 살펴보니 stack_clear의 두번째 인자(함수포인터)로 free를 넘겨주는거 같은데요
그러면 굳이 함수를 인자로 받을 필요가 있는지 궁금합니다.
인자로 받지 않고 그냥 내부에서 free로 구현하면 안되나 싶어서요.
free이외의 다른 함수 포인터가 들어오는 경우가 있어서 그런가요?

다시한번 자료구조를 실습해 볼수 있게 올려주신점 감사드립니다!! 
공부하는데 큰 도움이 되네요

**Comment by nadarm** [comment]
data가 단순 1차원적인 값이라면 free만으로 메모리 해제가 가능합니다
그런데 
struct a {
    int *arr;
    char *str;
}
같이 2차원 이상의 값이라면 단순 free 함수만으로는 arr와 str이 메모리가 해제되지 않아서 메모리 릭이 발생할 수 있습니다

**Comment by taelee42** [comment]
답변 감사드립니다. 
덕분에 이해했습니다. 
data가 1차원이 아닐수도 있다는 생각을 못했네요
